### ISSUE TITLE
Bug report: File links and file expose over the web 

### ISSUE THREAD

**Issue by JFDevelopments** [filegator/filegator#11]
**Bug 1:**
When you create a new user (user B) with separate folder to other users (user A). The file link generated by the user A allow to be used by user B when they have same file uploaded. 

**Expected behavior**
- It would be better if each user file have unique file link.
- The file link generated by the user A should not be used by user B when they have same file uploaded.

**Bug 2:**
The default file storage or folder (/repository) is accessible on the web.
Example: www.domain.com/filegator/repository/
The files are visible and downloadable by anyone.

**Expected behavior**
- By default the folder (/repository) permission and execution must set to restricted access by public.

**Comment by alcalbg** [comment]
Hi,

Thank you for reporting this.

1. Links are not generated, actually, they are simple hashed filenames. If filename happens to be the same, the link will be identical. However, both users will download different files (their own version). The whole sharing part needs to be upgraded to something better, suggestions are welcome.

2. If you put the script into a subfolder, repository and everything else including vendor, logs and user file could be exposed. This is not how the script should be installed https://docs.filegator.io/install.html You should configure your web server's web root to be the `dist` directory. See how this bug is not reproducable on demo: https://demo.filegator.io/repository

**Comment by JFDevelopments** [comment]
Thanks man! I appreciate your response.
