### ISSUE TITLE
Faq updated?

### ISSUE THREAD

**Issue by xmanag3r** [filegator/filegator#252]
Hello i have tried to add some notifications but no files are existing in /include

I want to add notification for email..but the code is updated and faq is not...

Help me

https://filegator.io/faq/

-------------------------------------
Can I add some actions after file is uploaded? like send an email notification or change the file-name?
Yes, look for this line in filegator/include/blueimp/server/php/upload.class.php

move_uploaded_file($uploaded_file, $file_path);
            
and add you custom code after or before that line, something like this email notification:

mail('me@example.com', 'Subject', 'New file uploaded');
            
You can access current user’s parameters such as username, email, homedir or permissions via $_SESSION[‘simple_auth’] variable. See this example:

mail('me@example.com', 'Subject', 'New file uploaded by the user: '.$_SESSION['simple_auth']['username']);
            
More complex example using current SMTP configuration:

$gator = new gator();
$gator->sendEmail('admin@example.com', 'Notification', 'New file uploaded by the user: '.$_SESSION['simple_auth']['username']); // admin
$gator->sendEmail($_SESSION['simple_auth']['email'], 'Notification', 'New file uploaded: '.$file->name); // user

**Comment by alcalbg** [comment]
This faq is for filegator older versions <7.0

**Comment by VE3PUE** [comment]
I know that the FAQ for older filegator versions <7.0 lists a method of sending notifications that no longer works ... BUT, how should (or can) email notifications be implemented now?

It looks like the MonoLog system could be used to send such emails, but I am not a developer and have no idea how to implement such a function.

To be clear, all I want to do is send an email to an admin that says the equivalent of "Some files have been uploaded to your repository". I do not need the files or the user to be identified since I am using Filegator for Guest uploads only.
