### ISSUE TITLE
Anonymous login as specific ldap-user without correct password possible

### ISSUE THREAD

**Issue by tmq96gh** [filegator/filegator#257]
**Description**
If LDAP-Adapter is configured and the ldap_server accepts "anonymous bind" (https://www.php.net/manual/en/function.ldap-bind.php) you can provoke a login as an existing user without knowing his password.

**To Reproduce**
1.) Type existing UID and rubbish Password; Press Login (Login-Form does not get cleared)
2.) change UID to rubbish UID; Press Login 
3.) change UID to existing UID; Press Login -> you now should be logged in (not as an anonymous User - as the giben UID)

**Expected behavior**
Since the User is not allowed to login via "anonymous bind" if a blank password is given - I think this behaviour is not desired.

If anonymous login is executed, I expected the user to be named something like anonymous.
If login-form is not cleared, I extected the password not be interpreted as "empty".

**Environment (please complete the following information):**
 - FileGator Version 7.6.0
 - Debian GNU/Linux 10 (buster)
 - PHP 7.2.34
 - Browser: Chrome, Edge, Firefox, Safari

**Comment by alcalbg** [comment]
cc @ahaenggli @lzkill

**Comment by ahaenggli** [comment]
Thx for reporting (and the mention)!

An anonymous login should not be possible because of [this line](https://github.com/filegator/filegator/blob/master/backend/Services/Auth/Adapters/LDAP.php#L76). Instead of anonymous you could use the filegator 'guest'-user.

A quick fix could be to add `if(!isset($password) || empty($password)) return false;` after [this line](https://github.com/filegator/filegator/blob/master/backend/Services/Auth/Adapters/LDAP.php#L210) of code. So empty passwords are not verified/rejected.
I'll try to activate the anonymous binding on the weekend to test it out.

**Comment by tmq96gh** [comment]
Thx for the fast reply.

@ahaenggli - the quick fix you mentioned works.
