### ISSUE TITLE
FileGator v4.3.2

### ISSUE THREAD

**Issue by jahabar** [filegator/filegator#54]
Hi
I bought filegator from Codecanyon few years back and got the ver FileGator v4.3.2 from you the last time. However the free download ver 7.33 is totally different from the commercial version. How do I get any updated version after FileGator v4.3.2. Thank you

**Comment by alcalbg** [comment]
Hi,

First of all, thank you all for supporting commercial version of FileGator. The first version was released on September 19th 2012. Since then, we've gone a long way and I believe there is still a lot to improve and accomplish. During those years, many things changed, many new technologies emerged (SPA) while others became obsolete (jQuery). FileGator had to go forward and that's why there will be no more updates or new releases of older versions. I encourage you all to switch to the latest open source version v7 which is the only one active and regularly maintained.

There are several reasons why we switched to open source model and GitHub.

Basically, we wanted to increase:

- Code quality by bringing more developers on board
- Code auditability and visibility
- Security
- Project lifetime

Unfortunately, there is no clear upgrade path from older versions. If you have the older version (version 5 or below) I recommend these steps to install v7:

- Backup everything
- Download the latest version from [here](https://docs.filegator.io/install.html)
- Install the fresh version of the latest FileGator in a separate folder, login as admin and change your password
- Move your whole `repository/` folder from the older version to the new one. Alternatively, you can configure [storage adapter](https://docs.filegator.io/configuration/storage.html) and set your old repository folder as root
- Re-create your users and their setup in the new version
- Check if everything works as expected
