### ISSUE TITLE
What's the policy when it comes to contributing?

### ISSUE THREAD

**Issue by AnixPasBesoin** [filegator/filegator#95]
I've been playing with FileGator's code base and it's very well done! Thank you for open-sourcing such a great tool.
I've read in the README file that FileGator aims to be "framework free", and that was very noticeable in the backend code (a from scratch implementation of an MVC architcture) which is great, but that lead me to think that any extra dependency isn't really welcomed in the code base.

For instance, I was willing to add a password scoring feature that would prevent account creation with weak passwords, but was kinda hesitating to submit it as PR since it has an extra composer dependency...

Would such a PR be welcomed or would it violate what FileGator is trying to be? I'd really appreciate your clarifications on this matter!

**Comment by alcalbg** [comment]
Hi,

Thank you for this great question!

I'm not against extra dependencies but they must be justified and implemented properly, in a way that they can be easily swapped with alternatives. This is not always possible but this was my goal.

Composer dependencies are tricky because you cannot compile the code or minify them. I've noticed that people are using compiled version a lot, they just download the script, unzip the file and upload everything to their server with ftp. If you have a ton of files in the vendor directory, that can be really slow. On the other hand, npm can be compiled into few js and css files and that's it, everything else can be deleted.

There already is a validation library included https://github.com/rakit/validation so maybe that can be used for the password scoring feature? I can see that they support custom rules, so it's worth checking.

**Comment by AnixPasBesoin** [comment]
Thank you for your clear and detailed answer!  ^_^

In my case, the password scoring library I worked with is [bjeavons/zxcvbn-php](https://github.com/bjeavons/zxcvbn-php), which is a bit more advanced than what's offered in [rakit/validation](https://github.com/rakit/validation). It's pretty much what [Dropbox uses](https://dropbox.tech/security/zxcvbn-realistic-password-strength-estimation) but ported in PHP.

IMOO, that's an extra dependency that is worth having in FileGator, and I'd really like to have your opinion on that specific matter!

Thank you again!

**Comment by alcalbg** [comment]
This lib is about 2MB in size which is like 1/3 of the current filegator's size. I'm not sure if a single feature should increase size that much.

It would be better to create some kind of 'advanced auth adapted' for filegator, with some other features included as well. Personally, I would like to see 2FA and maybe some kind of captcha.

**Comment by alcalbg** [comment]
To sum this up, in FileGator, simplicity is a feature, and because of that, we have to leave out some other features that add complexity.

**Comment by AnixPasBesoin** [comment]
A separate authentication adapter sounds like a great solution for such a use case.
Huge thanks for your time and clarifications! Keep up the great work!

**Comment by AnixPasBesoin** [comment]
A separate authentication adapter sounds like a good solution for such a use case.
Huge thanks for your time and clarifications! Keep up the greatwork!
